### ISSUE TITLE
about  rakutentech sdk

### ISSUE THREAD

**Issue by delokman** [rakutentech/ios-miniapp#124]
hello

what kind of miniapp package(wechat/tencent/buido) can render by rakutentech sdk?

how i can develop sdk to support specific miniapp package?

thanks a lot

**Comment by corycaywood** [comment]
Hi @delokman . I answered these questions in the issue from our Android repo. This repo (iOS) uses the same approach and architecture as our Android repo, so please see the answers there: 
https://github.com/rakutentech/android-miniapp/issues/129
