### ISSUE TITLE
How to config some environment variables XCode

### ISSUE THREAD

**Issue by i1020242** [rakutentech/ios-miniapp#446]
![Screen Shot 2022-10-28 at 16 24 06](https://user-images.githubusercontent.com/3816907/198553946-b6191b8a-36eb-42fc-a80d-30f8110e587f.png)

How to get these ID, for exaple: RASProjectId=test-project-id

**Comment by rleojoseph** [comment]
@i1020242 , These configurations can be set at your bash profile and if you continue following our development steps, these configurations will be auto-fetched by `pod install`.
If you want to know what are these configurations and what they can do, you have to be part of our [Rakuten Mini App platform ](https://developers.rakuten.com/miniapp/)

Let me know if you need more information.

**Comment by rleojoseph** [comment]
Closing this issue as there is no update
